name: entity
version: 0.8.5
description: > 
  A simple ORM for Relational and NoSQL database, such as Couchbase and PostgreSQL.
authors:
- Tom Yeh <tomyeh@rikulo.org>
homepage: https://github.com/rikulo/entity
documentation: https://github.com/rikulo/entity
dev_dependencies:
  test: any
  browser: any
  couchclient: any
  postgresql: any
  postgresql2: any
environment:
  sdk: ">=1.4.0"
dependencies:
